# Generated by Django 4.2.6 on 2023-12-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_name', models.CharField(max_length=100)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.country')),
            ],
        ),
    ]
